### ISSUE TITLE
Atlantean High Score saving unavailable

### ISSUE THREAD

**Issue by dennisranker** [agg23/openfpga-pcengine#5]
When launching Atlantean, the first screen shows the following message:

> 255 255
>
> FAILED TO CREATE HIGH SCORE FILE
> POSSIBLE BRAM FORMAT REQUIRED!
> 
> NO HIGH SCORES WILL BE SAVED!
> 
> PRESS RUN TO PLAY ATLANTEAN!

As far as I can tell there is no other impact, happy to provide any further info

**Comment by agg23** [comment]
For some reason that game doesn't have a provision for initializing a memory card. Every game in this core gets it's own memory card, instead of sharing it like it would in real life. You can fix this by copying a save file from a game that has initialized memory, and overwrite the existing Atlantean save file.

I guess I should preinitialize memory to be the same as a memory card...
